# Generated by Django 5.2.17 on 2026-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='evidence_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
